name: SuperSurvival
version: '${version}'
main: org.hugliodev.supersurvival.Main
api-version: '1.21'
depend:
  - PlaceholderAPI

commands:
  #admin
  back:
  clearchat:
  enchant:
  fly:
  gamemode:
  lockchat:
  supersurvivalreload:
  sctoggle:
  tp:
  setwarp:
  setspawn:
  staffchat:

  #player
  help:
  home:
  loc:
  msg:
  sethome:
  spawn:
  tpa:
  tpaccept:
  tpcancel:
  tpdecline:
  warp: